### PR TITLE
Fix CI error and upgrade rust version to 1.67.1

### PR DESCRIPTION
**Pull request by pzheng1025**

### CODE REVIEW

**Comment by pwang7** [comment]
Seems the CI still fails

**Comment by pwang7** [comment]
docker: Error response from daemon: manifest for gcr.io/etcd-development/etcd:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/etcd-development/etcd/manifests/latest".

**Comment by pwang7** [comment]
error: timed out waiting for the condition on pods/csi-controller-datenlord-0

**Review by ActivePeter — DISMISSED** [review]
All tests passed.

**Review by ActivePeter — COMMENTED** [review]
Ok now.

**Review by pwang7 — APPROVED** [review]

**Pull request merged**
