### PR TITLE
feat: make FUSE device IO asynchronous

### PR DESCRIPTION
**Pull request by Reto911**
In this PR, we avoided to use raw FUSE fd to interact with FUSE kernel module, by wrapping the raw fd with `std::fs::File`. And separated threads are used to receive FUSE requests, for avoiding invoking `spawn_blocking` always.

`IoVec` is deprecated, we use `std::io::IoSlice` now.

Besides, in this PR, we use `worker fd` for each FUSE request handlers, reducing potential resources race.

### CODE REVIEW

**Comment by Reto911** [comment]
Related issues:
- #495
- #10 
- #28

**Comment by frostyplanet** [comment]
Current worker flow in this PR:
`setup_buffer_pool -> (10 buffer)
-> fuse_device_reader  -> run loop request_rx [(file, byte_buffer, size)]  -> handle_fuse_request_res()  ->spawn`

Questions:
1. fuse_device_reader() is able to read the `File`  concurrently?  
2. loop request_rs  does nothing only to pass the request to handle_fuse_request_res() , which can be put into fuse_device_reader(), thus elimate a channel passing.
3.  handle_fuse_request_res() also does nothing only to spawn(),  which can be put into fuse_device_reader()
4. I think it might be cleaner to Remove `File` from ReplyRaw,  move the reponse writing to dedicated thread, thus remove the lifetime mark

**Comment by Reto911** [comment]
> Current worker flow in this PR: `setup_buffer_pool -> (some preallocated buffers) -> fuse_device_reader -> run loop request_rx [(file, byte_buffer, size)] -> handle_fuse_request_res() ->spawn`
> 
> Questions:
> 
>     1. fuse_device_reader() is able to read the `File`  concurrently?
> 
>     2. loop request_rs  does nothing only to pass the request to handle_fuse_request_res() , which can be put into fuse_device_reader(), thus elimate a channel passing.
> 
>     3. handle_fuse_request_res() also does nothing only to spawn(),  which can be put into fuse_device_reader()
> 
>     4. I think it might be cleaner to Remove `File` from ReplyRaw,  move the reponse writing to dedicated thread, thus remove the lifetime mark

1. Multiple threads cannot read a SINGLE `File` concurrently. However, in the case of ours, the two reader threads read requests from different FUSE worker `fd`s, they are cloned by `ioctl` but not via `dup`. In this case, the kernel will not lock the FUSE device on file-level, but a fine grit lock inside FUSE's kernel module, which makes the threads can read concurrently.
2. `fuse_device_reader` is not within tokio's async runtime context, therefore, we cannot spawn a task or invoke any async function here. To make the received requests can be handled within async context, we must pass the result to an async task via a channel.
3. Same as above, we cannot spawn an async task in `fuse_device_reader`.
4. I think there is no need to move the writing of response into a dedicated thread, because this writing is just a light-weight operation. Writing response in place (in tokio worker threads) can make full use of the spawned threads, which may be better to spawn dedicated threads. If we need to remove the lifetime mark from `Reply*`, I can make the `&mut File` as a parameter of `send_raw_message` method, thus the `ReplyEmpty` struct will not hold any `File` and `fd`, and `Reply*` structs will just perform as an encoder.

**Review by frostyplanet — APPROVED** [review]
LGTM

**Pull request merged**
