### PR TITLE
fix: Remove lazy_static

### LINKED ISSUE #475: Remove `lazy_static`
With the stabilization of `std::sync::OnceLock` (in 1.70.0), there seems to be better alternatives of `lazy_static`. The crate is not deprecated formally, but is not maintained, and urges users to move to `OnceLock`: https://github.com/rust-lang-nursery/lazy-static.rs/issues/214, https://github.com/rust-lang-nursery/lazy-static.rs/pull/216.

Therefore, I propose that we switch to another solution of static vars:
1. `std::sync::OnceLock`:
```rust
use std::collections::HashMap;
use std::sync::OnceLock;

fn hashmap() -> &'static HashMap<u32, &'static str> {
    static HASHMAP: OnceLock<HashMap<u32, &str>> = OnceLock::new();
    HASHMAP.get_or_init(|| {
        let mut m = HashMap::new();
        m.insert(0, "foo");
        m.insert(1, "bar");
        m.insert(2, "baz");
        m
    })
}

fn main() {
    // First access to `HASHMAP` initializes it
    println!("The entry for `0` is \"{}\".", hashmap().get(&0).unwrap());

    // Any further access to `HASHMAP` just returns the computed value
    println!("The entry for `1` is \"{}\".", hashmap().get(&1).unwrap());
}
```
2. `std::sync::LazyLock`:
Similar to `lazy_static`. **However, this is an unstable feature now.**

```rust
#![feature(lazy_cell)]

use std::collections::HashMap;

use std::sync::LazyLock;

static HASHMAP: LazyLock<HashMap<i32, String>> = LazyLock::new(|| {
    println!("initializing");
    let mut m = HashMap::new();
    m.insert(13, "Spica".to_string());
    m.insert(74, "Hoyten".to_string());
    m
});

fn main() {
    println!("ready");
    std::thread::spawn(|| {
        println!("{:?}", HASHMAP.get(&13));
    }).join().unwrap();
    println!("{:?}", HASHMAP.get(&74));

    // Prints:
    //   ready
    //   initializing
    //   Some("Spica")
    //   Some("Hoyten")
}
```
3. `once_cell::Lazy`
This is the prototype of `std::sync::LazyLock`, whose interfaces are similar to the `std` one.

At present, the use of `lazy_static` is very rare in our project, so it's cheap for us to switch to a new solution:
- [x] `async_fuse::metrics`
- [ ] `csi::util`

### PR DESCRIPTION
**Pull request by lord2anil**
Removed the usage of lazy_static and replaced it with once_cell::Lazy

closes #475

### CODE REVIEW

**Comment by Reto911** [comment]
Thank you for your contributions! Before we can approve your PR, you may need to ensure that some significant checks, such as `fmt`, `clippy` and `KIND-K8S-CSI-E2E`, pass. Generally, please run `cargo fmt --all` and `cargo clippy --all-features --all-targets` before committing your codes.

Besides, please ensure that the commit titles follow the Conventional Commits specification, which you can find here: [Conventional Commits 1.0.0](https://www.conventionalcommits.org/en/v1.0.0/). The title of the PR should also follow the same convention.

You can use forced-push on your own branch to fix such problems.

**Comment by Reto911** [comment]
LGTM, thanks. Finally, please squash your three commits into a single one and do forced-push, to make the log of the repo tidy. And please remember to reword the squashed commit message to make it follow the convention.

**Comment by lord2anil** [comment]
Thanks for guiding me. all Done

**Review by Reto911 — APPROVED** [review]

**Comment by Reto911** [comment]
Hi, as you have allowed maintainers to edit this PR, I tried to reword the commit message to make it follow the convention, and pushed it to your branch. As the checks pass, we will merge the PR. Again, thanks for your contribution!

**Pull request merged**
